//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9148
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9148.
// 
namespace ContainerLoading.ContainerService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://10.11.1.28/ContainerService/service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRequiredClientVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRequiredClientVersion() {
            object[] results = this.Invoke("GetRequiredClientVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRequiredClientVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRequiredClientVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRequiredClientVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadScannedBarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadScannedResult UploadScannedBarcode(UploadScannedBarcodeTableRow[] scannedBarcodes) {
            object[] results = this.Invoke("UploadScannedBarcode", new object[] {
                        scannedBarcodes});
            return ((UploadScannedResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadScannedBarcode(UploadScannedBarcodeTableRow[] scannedBarcodes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadScannedBarcode", new object[] {
                        scannedBarcodes}, callback, asyncState);
        }
        
        /// <remarks/>
        public UploadScannedResult EndUploadScannedBarcode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UploadScannedResult)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadScannedBarcodeTableRow {
        
        private string containerBarcodeField;
        
        private string palletBarcodeField;
        
        private int statusField;
        
        private string errMsgField;
        
        private string updatedByField;
        
        private int designationField;
        
        private string forkliftField;
        
        private string bracerField;
        
        private string matCheckerField;
        
        private string loadCheckerField;
        
        private string casualCheckerField;
        
        private string dataCheckerField;
        
        /// <remarks/>
        public string ContainerBarcode {
            get {
                return this.containerBarcodeField;
            }
            set {
                this.containerBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public string PalletBarcode {
            get {
                return this.palletBarcodeField;
            }
            set {
                this.palletBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public int Designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
            }
        }
        
        /// <remarks/>
        public string Forklift {
            get {
                return this.forkliftField;
            }
            set {
                this.forkliftField = value;
            }
        }
        
        /// <remarks/>
        public string Bracer {
            get {
                return this.bracerField;
            }
            set {
                this.bracerField = value;
            }
        }
        
        /// <remarks/>
        public string MatChecker {
            get {
                return this.matCheckerField;
            }
            set {
                this.matCheckerField = value;
            }
        }
        
        /// <remarks/>
        public string LoadChecker {
            get {
                return this.loadCheckerField;
            }
            set {
                this.loadCheckerField = value;
            }
        }
        
        /// <remarks/>
        public string CasualChecker {
            get {
                return this.casualCheckerField;
            }
            set {
                this.casualCheckerField = value;
            }
        }
        
        /// <remarks/>
        public string DataChecker {
            get {
                return this.dataCheckerField;
            }
            set {
                this.dataCheckerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadScannedResult {
        
        private int serverStatusField;
        
        private string serverMessageField;
        
        private UploadScannedBarcodeTableRow[] uploadedDataField;
        
        /// <remarks/>
        public int ServerStatus {
            get {
                return this.serverStatusField;
            }
            set {
                this.serverStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ServerMessage {
            get {
                return this.serverMessageField;
            }
            set {
                this.serverMessageField = value;
            }
        }
        
        /// <remarks/>
        public UploadScannedBarcodeTableRow[] UploadedData {
            get {
                return this.uploadedDataField;
            }
            set {
                this.uploadedDataField = value;
            }
        }
    }
}
